# Generated by Django 5.0 on 2024-05-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Haus'), (1, 'Pfadfinderzeltplatz'), (2, 'Campingplatz'), (3, 'Freier Platz'), (4, 'Privater Platz')], help_text='Typ des Platzes', null=True),
        ),
    ]
