# Generated by Django 5.0 on 2025-01-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_trip_owner_tripconstruction_owner'),
        ('main', '0006_membership_event_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripconstruction',
            name='owner',
        ),
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Lager'), (1, 'Fahrt'), (2, 'Haik'), (3, 'Tagesaktion')], null=True),
        ),
        migrations.AlterField(
            model_name='tripconstruction',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
