# Generated by Django 5.0 on 2025-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_tripconstruction_owner_location_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tn_female_a16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='tn_female_u16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='tn_male_a16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='tn_male_u16',
            field=models.IntegerField(default=0),
        ),
    ]
