# Generated by Django 5.0 on 2025-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_trip_tn_female_a16_trip_tn_female_u16_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripconstruction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
