# Generated by Django 5.0 on 2025-01-25 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_packedmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='location',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Haus'), (1, 'Pfadfinderzeltplatz'), (2, 'Campingplatz'), (3, 'Freier Platz'), (4, 'Privater Platz')], null=True, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tn_count',
            field=models.IntegerField(default=0, verbose_name='TN-Anzahl'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tn_female_a16',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TN weiblich über 16'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tn_female_u16',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TN weiblich unter 16'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tn_male_a16',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TN männlich über 16'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tn_male_u16',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TN männlich unter 16'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Lager'), (1, 'Fahrt'), (2, 'Haik'), (3, 'Tagesaktion')], null=True, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='tripconstruction',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='tripconstruction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung'),
        ),
    ]
