# Generated by Django 5.0 on 2025-01-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_tripgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tn_count',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tn_female_a16',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tn_female_u16',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tn_male_a16',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tn_male_u16',
        ),
        migrations.AlterField(
            model_name='tripgroup',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Gruppenname'),
        ),
    ]
