# Generated by Django 5.0 on 2025-02-19 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_alter_material_weight'),
        ('events', '0013_remove_trip_tn_count_remove_trip_tn_female_a16_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl')),
                ('description', models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.material')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.trip')),
            ],
        ),
    ]
