# Generated by Django 5.0 on 2025-04-11 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_trip_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmaterial',
            name='reduce_from_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
