# Generated by Django 5.0 on 2025-04-12 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_tripmaterial_reduce_from_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripmaterial',
            old_name='reduce_from_stock',
            new_name='reduced_from_stock',
        ),
        migrations.AddField(
            model_name='tripmaterial',
            name='previous_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
