# Generated by Django 5.0 on 2025-04-12 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_rename_reduce_from_stock_tripmaterial_reduced_from_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmaterial',
            name='reduced_total_from_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
