# Generated by Django 5.0 on 2025-04-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_tripmaterial_reduced_total_from_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripmaterial',
            name='reduced_total_from_stock',
        ),
    ]
