# Generated by Django 5.0 on 2025-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_tripmaterial_reduced_total_from_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Lager'), (1, 'Fahrt'), (2, 'Haik'), (3, 'Tagesaktion'), (4, 'Material-Verleih')], null=True, verbose_name='Typ'),
        ),
    ]
