# Generated by Django 5.0 on 2025-04-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_trip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung / Bei Material-Verleih Empfänger Organisation (Groß- / Kleinschreibung beachten!)'),
        ),
    ]
