# Generated by Django 5.0 on 2025-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Empfänger Organisation (Groß- / Kleinschreibung beachten!)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung'),
        ),
    ]
