# Generated by Django 5.0 on 2025-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_trip_recipient_alter_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='reciepentcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Empfängercode für den Materialverleih'),
        ),
    ]
