# Generated by Django 5.0 on 2025-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_trip_reciepentcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='reciepentcode',
        ),
        migrations.AddField(
            model_name='trip',
            name='recipientcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Empfängercode der empfangenden Organisation'),
        ),
    ]
