# Generated by Django 5.0 on 2025-07-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_trip_recipient_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='recipient',
        ),
    ]
