# Generated by Django 5.0 on 2025-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_eventplanningchecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplanningchecklistitem',
            name='maturity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
