# Generated by Django 5.0 on 2025-09-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_eventplanningchecklistitem_maturity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventplanningchecklistitem',
            old_name='maturity',
            new_name='due_date',
        ),
    ]
