# Generated by Django 5.0 on 2025-09-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_rename_maturity_eventplanningchecklistitem_due_date'),
        ('main', '0014_organization_pro1'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplanningchecklistitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='main.organization'),
        ),
        migrations.AlterField(
            model_name='eventplanningchecklistitem',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='events.trip'),
        ),
    ]
