# Generated by Django 5.0 on 2025-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_eventplanningchecklistitem_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplanningchecklistitem',
            name='title',
            field=models.CharField(max_length=2255),
        ),
    ]
