# Generated by Django 5.0 on 2025-09-07 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0023_remove_material_temporary_and_more'),
        ('events', '0035_alter_eventplanningchecklistitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='stockmaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist', to='buildings.stockmaterial'),
        ),
    ]
