# Generated by Django 5.0 on 2025-09-12 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_shoppinglistitem_stockmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planners',
            field=models.ManyToManyField(blank=True, related_name='planned_trips', to=settings.AUTH_USER_MODEL, verbose_name='Planer'),
        ),
    ]
