# Generated by Django 5.0 on 2026-01-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_trip_planners'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='product_group',
            field=models.IntegerField(blank=True, choices=[(0, 'Getränke'), (1, 'Konserven'), (2, 'Backwaren'), (3, 'Aufschnitt'), (4, 'Grillgut'), (5, 'Werkzeug'), (6, 'Material'), (7, 'Hygiene')], null=True, verbose_name='Warengruppe'),
        ),
    ]
