# Generated by Django 5.0 on 2026-01-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_shoppinglistitem_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='product_group',
            field=models.IntegerField(blank=True, choices=[(0, 'Getränke'), (1, 'Brot / Cerealien'), (2, 'Obst / Gemüse'), (3, 'Kühlung'), (4, 'Grillgut'), (5, 'Konserven'), (6, 'Snacks'), (7, 'Hygiene'), (8, 'Werkzeug'), (9, 'Material'), (99, 'Sonstiges')], null=True, verbose_name='Warengruppe'),
        ),
    ]
