# Generated by Django 5.0 on 2026-01-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_alter_shoppinglistitem_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, default='', max_length=200, verbose_name='Kurz-Beschreibung')),
                ('description', models.CharField(blank=True, default='', max_length=2048, verbose_name='Beschreibung')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Mahlzeit'), (1, 'Workshop'), (2, 'Dienst'), (3, 'Mahlzeiten-Dienst'), (4, 'Abendprogramm'), (99, 'Sonstiges')], null=True, verbose_name='Typ')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programm', to='events.trip')),
            ],
        ),
    ]
