# Generated by Django 5.0 on 2026-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_programmitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmitem',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='programmitem',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='programmitem',
            name='type',
            field=models.IntegerField(choices=[(0, 'Mahlzeit'), (1, 'Workshop'), (2, 'Dienst'), (3, 'Mahlzeiten-Dienst'), (4, 'Abendprogramm'), (99, 'Sonstiges')], null=True, verbose_name='Typ'),
        ),
    ]
