# Generated by Django 5.0 on 2026-01-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_alter_programmitem_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmitem',
            name='visible_for_members',
            field=models.BooleanField(default=True, verbose_name='Sichtbar für Mitglieder'),
        ),
    ]
