# Generated by Django 5.0 on 2026-02-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_programmitem_visible_for_members'),
        ('knowledgebase', '0007_alter_recipetag_name_alter_recipetag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmitem',
            name='recipe',
            field=models.ForeignKey(blank=True, help_text='Nur für Mahlzeiten', null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledgebase.recipe', verbose_name='Rezept'),
        ),
    ]
