# Generated by Django 5.0 on 2026-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_programmitem_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung'),
        ),
    ]
