# Generated by Django 5.0 on 2026-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_trip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, default='', max_length=3000, verbose_name='Beschreibung'),
        ),
    ]
