# Generated by Django 5.2.15 on 2026-08-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0025_materialcontainer_stockmaterial_container_and_more'),
        ('events', '0045_alter_trip_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackedStockMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed', models.BooleanField(default=False)),
                ('stock_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_for_trips', to='buildings.stockmaterial')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_stock_materials', to='events.trip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trip', 'stock_material'), name='unique_packed_stock_material_per_trip')],
            },
        ),
    ]
