# Generated by Django 5.0 on 2026-02-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_recipetag_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Beschreibung'),
        ),
    ]
