# Generated by Django 5.0 on 2026-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich'),
        ),
    ]
