# Generated by Django 5.0 on 2026-02-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_recipetag_is_public'),
        ('main', '0020_membership_knowledge_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tags', to='main.organization'),
        ),
    ]
