# Generated by Django 5.0 on 2026-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0006_recipetag_owner'),
        ('main', '0020_membership_knowledge_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='recipetag',
            unique_together={('name', 'owner')},
        ),
    ]
