# Generated by Django 5.0 on 2026-02-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_alter_recipetag_name_alter_recipetag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='product_group',
            field=models.IntegerField(blank=True, choices=[(0, 'Getränke'), (1, 'Brot / Cerealien'), (2, 'Obst / Gemüse'), (3, 'Kühlung'), (4, 'Grillgut'), (5, 'Konserven'), (6, 'Snacks'), (7, 'Hygiene'), (8, 'Werkzeug'), (9, 'Material'), (99, 'Sonstiges')], null=True, verbose_name='Warengruppe'),
        ),
    ]
