# Generated by Django 5.2.15 on 2026-08-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
        ('main', '0029_organization_pro6_membership_leiterrundenmitglied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='account_holder',
            field=models.CharField(blank=True, max_length=70, verbose_name='Kontoinhaber'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_cashbooks', to='main.membership', verbose_name='Verantwortlicher Kassenwart'),
        ),
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Auslage')),
                ('expense_date', models.DateField(verbose_name='Belegdatum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('attachment', models.FileField(upload_to='cashbooks/reimbursements/%Y/%m/', verbose_name='Beleg')),
                ('recipient_name', models.CharField(max_length=70, verbose_name='Kontoinhaber')),
                ('recipient_iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('recipient_bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=10, verbose_name='Status')),
                ('review_note', models.TextField(blank=True, verbose_name='Prüfvermerk')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sepa_exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_requests', to='cashbook.cashbook', verbose_name='Kassenbuch')),
                ('cashbook_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_request', to='cashbook.cashbookentry')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashbook_reimbursement_requests', to=settings.AUTH_USER_MODEL, verbose_name='Antragsteller')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reimbursement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
