# Generated by Django 5.2.15 on 2026-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_cashbook_account_holder_cashbook_bic_cashbook_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='recipient_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=70, verbose_name='Kontoinhaber'),
        ),
    ]
