# Generated by Django 5.2.15 on 2026-08-27 16:43

from django.conf import settings
from django.db import migrations, models


def mark_existing_automatic_bank_entries(apps, schema_editor):
    CashBookEntry = apps.get_model("cashbook", "CashBookEntry")
    AdvanceBudget = apps.get_model("cashbook", "AdvanceBudget")
    EventExpense = apps.get_model("cashbook", "EventExpense")
    ReimbursementRequest = apps.get_model("cashbook", "ReimbursementRequest")
    entry_ids = set(AdvanceBudget.objects.exclude(advance_entry_id=None).values_list("advance_entry_id", flat=True))
    entry_ids.update(AdvanceBudget.objects.exclude(settlement_entry_id=None).values_list("settlement_entry_id", flat=True))
    entry_ids.update(EventExpense.objects.exclude(cashbook_entry_id=None).values_list("cashbook_entry_id", flat=True))
    entry_ids.update(ReimbursementRequest.objects.exclude(cashbook_entry_id=None).values_list("cashbook_entry_id", flat=True))
    CashBookEntry.objects.filter(pk__in=entry_ids).exclude(cashbook__iban="").update(
        source="automatic",
        reconciliation_status="expected",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0006_alter_eventexpense_attachment'),
        ('events', '0046_packedstockmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='bank_import_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Bankimport-Fingerabdruck'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='bank_reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mit Bankumsatz abgeglichen am'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='reconciliation_status',
            field=models.CharField(choices=[('booked', 'Verbucht'), ('expected', 'Erwartete Kontobewegung')], default='booked', max_length=20, verbose_name='Bankabgleich'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuell'), ('automatic', 'Automatisch erzeugt'), ('bank_import', 'Bankimport')], default='manual', max_length=20, verbose_name='Quelle'),
        ),
        migrations.RunPython(mark_existing_automatic_bank_entries, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cashbookentry',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_import_fingerprint', ''), _negated=True), fields=('cashbook', 'bank_import_fingerprint'), name='cashbook_unique_bank_import'),
        ),
    ]
