# Generated by Django 5.0 on 2024-03-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_stockmaterial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StockMaterial",
        ),
    ]
