# Generated by Django 5.0 on 2024-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_stockmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
