# Generated by Django 5.0 on 2025-01-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='event_manager',
            field=models.BooleanField(default=False),
        ),
    ]
