# Generated by Django 5.0 on 2025-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_membership_admin_alter_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reciepentcode',
            field=models.CharField(default='iBFSqUJ8A8HvZD2rWB7f', max_length=20),
        ),
    ]
