# Generated by Django 5.0 on 2025-07-08 17:13

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_organization_reciepentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='reciepentcode',
            field=models.CharField(default=main.models.generate_recipient_code, max_length=20, verbose_name='Empfängercode für den Materialverleih'),
        ),
    ]
