# Generated by Django 5.0 on 2025-07-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_organization_reciepentcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='reciepentcode',
            new_name='recipientcode',
        ),
    ]
