# Generated by Django 5.0 on 2025-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_message_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pro1',
            field=models.BooleanField(default=False),
        ),
    ]
