# Generated by Django 5.0 on 2025-09-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_organization_pro1'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
