# Generated by Django 5.0 on 2025-09-07 08:51

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_organization_default_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_checklist',
            field=models.JSONField(blank=True, default=main.models.default_checklist_items),
        ),
    ]
