# Generated by Django 5.0 on 2026-01-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_organization_default_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pro2',
            field=models.BooleanField(default=False),
        ),
    ]
