# Generated by Django 5.0 on 2026-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_organization_pro2'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pro3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='pro4',
            field=models.BooleanField(default=False),
        ),
    ]
