# Generated by Django 5.0 on 2026-02-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_organization_pro3_organization_pro4'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='knowledge_manager',
            field=models.BooleanField(default=False),
        ),
    ]
