# Generated by Django 5.0 on 2026-03-24 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_alter_trip_description'),
        ('main', '0022_membership_cashier_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Startsaldo'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbooks', to='main.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='cashbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.cashbook', verbose_name='Kassenbuch'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='counterparty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zahlungspartner'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='entry_type',
            field=models.CharField(choices=[('income', 'Einnahme'), ('expense', 'Ausgabe')], max_length=10, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Belegnummer / Referenz'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='events.trip', verbose_name='Veranstaltung'),
        ),
    ]
