# Generated by Django 5.0 on 2026-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_cashbookentry_entry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='entry_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Nummer'),
        ),
    ]
