# Generated by Django 5.0 on 2026-03-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_cashbookentry_entry_number'),
        ('main', '0026_cashbookauditlog'),
    ]

    operations = [
    ]
