# Generated by Django 5.0 on 2023-12-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Construction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(default="", max_length=1024)),
                ("public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(default="", max_length=1024)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, help_text="Gewicht in kg", max_digits=10
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Dachplane"),
                            (1, "Zeltplane"),
                            (2, "Stange"),
                            (3, "Seil"),
                            (4, "Hering"),
                        ],
                        help_text="Typ des Materials",
                        null=True,
                    ),
                ),
                ("length_min", models.IntegerField(blank=True, null=True)),
                ("length_max", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ConstructionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.construction",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.material",
                    ),
                ),
            ],
        ),
    ]
