# Generated by Django 5.0 on 2024-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_material_owner_stockmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="construction",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="constructions/"),
        ),
        migrations.AddField(
            model_name="material",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="materials/"),
        ),
    ]
