# Generated by Django 5.0 on 2024-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_construction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='storage_place',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
