# Generated by Django 5.0 on 2024-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_material_storage_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='storage_place',
        ),
        migrations.AddField(
            model_name='constructionmaterial',
            name='storage_place',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
