# Generated by Django 5.0 on 2024-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_remove_material_storage_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaterial',
            name='storage_place',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
