# Generated by Django 5.0 on 2025-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_alter_material_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='covered_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='construction',
            name='required_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='construction',
            name='sleep_place_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
