# Generated by Django 5.0 on 2025-01-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_alter_construction_covered_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Dachplane'), (1, 'Zeltplane'), (2, 'Stange'), (3, 'Seil'), (4, 'Hering'), (5, 'Küchenmaterial'), (6, 'Verbrauchsmaterial')], help_text='Typ des Materials', null=True),
        ),
    ]
