# Generated by Django 5.0 on 2025-01-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_alter_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionmaterial',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
