# Generated by Django 5.0 on 2025-01-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_constructionmaterial_packed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionmaterial',
            name='packed',
        ),
    ]
