# Generated by Django 5.0 on 2025-01-25 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_remove_constructionmaterial_packed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='covered_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in m²', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Überdachte Fläche'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='constructions/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='required_space',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in m²', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Benötigte Fläche'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='sleep_place_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Schlafplatz-Anzahl'),
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='storage_place',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Lagerort'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='material',
            name='length_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in m', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximallänge'),
        ),
        migrations.AlterField(
            model_name='material',
            name='length_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in m', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mindestlänge'),
        ),
        migrations.AlterField(
            model_name='material',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Dachplane'), (1, 'Zeltplane'), (2, 'Stange'), (3, 'Seil'), (4, 'Hering'), (5, 'Küchenmaterial'), (6, 'Verbrauchsmaterial')], null=True, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='in kg', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gewicht'),
        ),
        migrations.AlterField(
            model_name='material',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in m', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Breite'),
        ),
        migrations.AlterField(
            model_name='stockmaterial',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='stockmaterial',
            name='storage_place',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Lagerort'),
        ),
    ]
