# Generated by Django 5.0 on 2025-01-27 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_alter_construction_covered_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='sleep_place_count',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Schlafplatz-Anzahl'),
        ),
        migrations.AlterField(
            model_name='material',
            name='length_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximallänge'),
        ),
        migrations.AlterField(
            model_name='material',
            name='length_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mindestlänge'),
        ),
        migrations.AlterField(
            model_name='material',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Breite'),
        ),
    ]
