# Generated by Django 5.0 on 2025-01-27 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_alter_construction_sleep_place_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='in kg', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gewicht'),
        ),
    ]
