# Generated by Django 5.0 on 2025-02-24 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_alter_material_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaterial',
            name='condition_broke',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Davon defekt'),
        ),
        migrations.AddField(
            model_name='stockmaterial',
            name='condition_healthy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Davon in Ordnung'),
        ),
        migrations.AddField(
            model_name='stockmaterial',
            name='condition_medium_healthy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Davon wartungsbedürftig'),
        ),
        migrations.AddField(
            model_name='stockmaterial',
            name='material_condition_description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Zustands-Beschreibung'),
        ),
    ]
