# Generated by Django 5.0 on 2025-04-11 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0018_stockmaterial_condition_broke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaterial',
            name='reduce_from_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
