# Generated by Django 5.0 on 2025-04-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0019_stockmaterial_reduce_from_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmaterial',
            name='reduce_from_stock',
        ),
    ]
