# Generated by Django 5.0 on 2025-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_remove_stockmaterial_reduce_from_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Beschreibung'),
        ),
    ]
