# Generated by Django 5.0 on 2025-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_alter_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
