# Generated by Django 5.0 on 2025-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0022_material_temporary_material_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='temporary',
        ),
        migrations.RemoveField(
            model_name='material',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='stockmaterial',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmaterial',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
