# Generated by Django 5.0 on 2026-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0023_remove_material_temporary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Dachplane'), (1, 'Zeltplane'), (2, 'Stange'), (3, 'Seil'), (4, 'Hering'), (5, 'Küchenmaterial'), (6, 'Verbrauchsmaterial'), (7, 'Werkzeug'), (8, 'Ersatzteil')], null=True, verbose_name='Typ'),
        ),
    ]
