# Generated by Django 5.2.15 on 2026-08-09 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0024_alter_material_type'),
        ('main', '0029_organization_pro6_membership_leiterrundenmitglied'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('storage_place', models.CharField(blank=True, default='', max_length=1024, verbose_name='Lagerort')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('scan_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR-Code')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_containers', to='main.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockmaterial',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='buildings.materialcontainer', verbose_name='Materialkiste'),
        ),
        migrations.AddConstraint(
            model_name='materialcontainer',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_material_container_name_per_org'),
        ),
    ]
