from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('trip', views.trip, name='trip'),
    path('trip/delete/<int:pk>/', views.delete_trip, name='delete_trip'),
    path('trip/edit/<int:pk>/', views.edit_trip, name='edit_trip'),
    path('trip/edit/', views.edit_trip, name='edit_trip'),
    path('trip/show/<int:pk>/', views.show_trip, name='show_trip'),
    path('trip/programm/<int:pk>/', views.programm, name='programm'),
    path('trip/programm/add_accumulated_ingredients/<int:pk>/', views.add_accumulated_ingredients, name='add_accumulated_ingredients'),
    path('trip/programm/<int:pk>/add/', views.add_programm_item, name='add_programm_item'),
    path('trip/programm/<int:item_id>/edit/', views.edit_programm_item, name='edit_programm_item'),
    path("trip/<int:pk>/print/", views.print_programm, name="print_programm"),
    path("trip/programm/<int:item_id>/show/", views.show_program_item, name="show_programm_item"),
    path("trip/programm/<int:item_pk>/add-recipe-to-shoppinglist/",views.add_recipe_to_shoppinglist,name="add_recipe_to_shoppinglist"),
    path('trip/shoppinglist/<int:pk>/', views.shoppinglist, name='shoppinglist'),
    path('trip/shoppinglist/autocomplete/', views.shoppinglist_auto_complete, name='shoppinglist-auto-complete'),
    path("trip/<int:trip_id>/shoppinglist/add/", views.add_shoppinglist_item, name="add_shoppinglist_item"),
    path("shoppinglist/update/", views.update_shoppinglist_item, name="update_shoppinglist_item"),
    path("shoppinglist/<int:item_id>/delete/", views.delete_shoppinglist_item, name="delete_shoppinglist_item"),
    path("trip/<int:trip_id>/vacancies/", views.trip_vacancies, name="trip_vacancies"),
    path("trip/<int:trip_id>/vacancies/add/", views.add_vacancy, name="add_vacancy"),
    path("vacancies/update/", views.update_vacancy, name="update_vacancy"),
    path("vacancies/<int:vacancy_id>/delete/", views.delete_vacancy, name="delete_vacancy"),
    path("trips/<int:trip_id>/checklist/", views.checklist, name="checklist"),
    path("trips/<int:trip_id>/checklist/add/", views.add_checklist_item, name="add_checklist_item"),
    path("checklist/<int:item_id>/toggle/", views.toggle_checklist_item, name="toggle_checklist_item"),
    path("checklist/<int:item_id>/delete/", views.delete_checklist_item, name="delete_checklist_item"),
    path("checklist/update-due-date/", views.update_checklist_due_date, name="update_checklist_due_date"),
    path('trip/<int:trip_id>/vacancies/export/', views.export_vacancies_csv, name='export_vacancies_csv'),
    path("trips/<int:trip_id>/vacancies/import/", views.import_vacancies_csv, name="import_vacancies_csv"),
    path('trip/check_trip_material/<int:pk>/', views.check_trip_material, name='check_trip_material'),
    path('location', views.location, name='location'),
    path('location/edit/<int:pk>/', views.edit_location, name='edit_location'),
    path('location/edit/', views.edit_location, name='edit_location'),
    path('location/show/<int:pk>/', views.show_location, name='show_location'),
    path('location/delete/<int:pk>/', views.delete_location, name='delete_location'),
    path('trip/summary/<int:pk>/', views.construction_summary, name='construction_summary'),
    path('trip/find_construction_combination/<int:pk>/', views.find_construction_combination,
         name='find_construction_combination'),
    path('trip/find_construction_combination_w_check_material/<int:pk>/',
         views.find_construction_combination_w_check_material, name='find_construction_combination_w_check_material'),
    path('save_constructions/<int:pk>/', views.save_constructions_for_trip, name='save_constructions_for_trip'),
    path('change-packed-material/', views.change_packed_material, name="change_packed_material"),
    path('trip/<int:trip_id>/download_trip_ics/', views.download_trip_ics, name='download_trip_ics'),
]
